sudo: required
services:
  - docker

before_install: 
  - docker build -t wahabwajahat/docker-react -f Dockerfile.dev .

script:
  - docker run wahabwajahat/docker-react npm run test -- --coverage

  node_js:
  - 8